### ISSUE TITLE
Hacking dom element prototype

### ISSUE THREAD

**Issue by mathewrapid** [sergonius/img-to-bg#1]
![One does not simply](https://i.imgflip.com/x5xuj.jpg)

https://github.com/sergonius/img-to-bg/blob/master/img-to-bg.js#L13
```
Element.prototype.remove = function() {
    this.parentElement.removeChild(this);
};
```

![Trololololo](https://cdn2.scratch.mit.edu/get_image/user/10217796_90x90.png)

**Comment by sergonius** [comment]
Feel free to create a PR :dancers:

**Comment by sergonius** [comment]
There you go.
